# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ea22c2ee1d84dc37c3749402d093d81faebd67057ae93e9522153a89ea5c14e5be1c697ca5c827590fad4c932fcd35148e63b2e4459e632d91d6c5496b520618

test:
  secret_key_base: 927e3b0fca0ecdab26876c861fdefcb89b013ef751321da04949895da9176a577d3f8d5a4f75b7b5a7655dc54ce272fbd1ea51f6c6d319dd5d941275e9ceb6de

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
